/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9-dev */

#include "protobuf/to-computer.nanopb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(fdbg_Ack, fdbg_Ack, AUTO)


PB_BIND(fdbg_WriteMemory, fdbg_WriteMemory, AUTO)


PB_BIND(fdbg_ReadMemory, fdbg_ReadMemory, AUTO)


PB_BIND(fdbg_Reset, fdbg_Reset, AUTO)


PB_BIND(fdbg_Step, fdbg_Step, AUTO)


PB_BIND(fdbg_Cycle, fdbg_Cycle, AUTO)


PB_BIND(fdbg_Breakpoint, fdbg_Breakpoint, AUTO)


PB_BIND(fdbg_UserEvent, fdbg_UserEvent, AUTO)


PB_BIND(fdbg_UserEvent_TerminalKeypress, fdbg_UserEvent_TerminalKeypress, AUTO)


PB_BIND(fdbg_Run, fdbg_Run, AUTO)


PB_BIND(fdbg_Next, fdbg_Next, AUTO)


PB_BIND(fdbg_GetRunStatus, fdbg_GetRunStatus, AUTO)


PB_BIND(fdbg_Pause, fdbg_Pause, AUTO)


PB_BIND(fdbg_ToComputer, fdbg_ToComputer, AUTO)




