/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9-dev */

#include "protobuf/to-debugger.nanopb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(fdbg_AckResponse, fdbg_AckResponse, AUTO)


PB_BIND(fdbg_WriteMemoryResponse, fdbg_WriteMemoryResponse, AUTO)


PB_BIND(fdbg_ReadMemoryResponse, fdbg_ReadMemoryResponse, AUTO)


PB_BIND(fdbg_ComputerStatus, fdbg_ComputerStatus, 2)


PB_BIND(fdbg_OptionalUint, fdbg_OptionalUint, AUTO)


PB_BIND(fdbg_CycleResponse, fdbg_CycleResponse, 2)


PB_BIND(fdbg_BreakpointList, fdbg_BreakpointList, AUTO)


PB_BIND(fdbg_ComputerEvent, fdbg_ComputerEvent, AUTO)


PB_BIND(fdbg_ComputerEvent_TerminalPrint, fdbg_ComputerEvent_TerminalPrint, AUTO)


PB_BIND(fdbg_RunStatus, fdbg_RunStatus, 2)


PB_BIND(fdbg_Debug, fdbg_Debug, 2)


PB_BIND(fdbg_ToDebugger, fdbg_ToDebugger, 2)




