/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9-dev */

#ifndef PB_FDBG_PROTOBUF_TO_DEBUGGER_NANOPB_H_INCLUDED
#define PB_FDBG_PROTOBUF_TO_DEBUGGER_NANOPB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _fdbg_Status {
    fdbg_Status_OK = 0,
    fdbg_Status_ERR_WRITING_MEMORY = 1,
    fdbg_Status_TOO_MANY_BREAKPOINTS = 2,
    fdbg_Status_INVALID_MESSAGE = 3,
    fdbg_Status_IO_SERIAL_ERROR = 4,
    fdbg_Status_CPU_INVALID_INSTRUCTION = 5
} fdbg_Status;

/* Struct definitions */
typedef struct _fdbg_AckResponse {
    uint32_t id;
    uint32_t server_sz;
    uint32_t to_computer_sz;
    uint32_t to_debugger_sz;
} fdbg_AckResponse;

typedef struct _fdbg_WriteMemoryResponse {
    uint64_t first_failed_pos;
} fdbg_WriteMemoryResponse;

typedef PB_BYTES_ARRAY_T(64) fdbg_ReadMemoryResponse_bytes_t;
typedef struct _fdbg_ReadMemoryResponse {
    uint64_t initial_pos;
    fdbg_ReadMemoryResponse_bytes_t bytes;
} fdbg_ReadMemoryResponse;

typedef struct _fdbg_OptionalUint {
    bool has;
    uint64_t value;
} fdbg_OptionalUint;

typedef struct _fdbg_CycleResponse {
    uint64_t pc;
    pb_size_t bytes_count;
    fdbg_OptionalUint bytes[16];
    pb_size_t bits_count;
    bool bits[24];
} fdbg_CycleResponse;

typedef struct _fdbg_BreakpointList {
    pb_size_t addr_count;
    uint64_t addr[16];
} fdbg_BreakpointList;

typedef struct _fdbg_ComputerEvent_TerminalPrint {
    char text[8];
} fdbg_ComputerEvent_TerminalPrint;

typedef struct _fdbg_ComputerEvent {
    pb_size_t which_type;
    union {
        fdbg_ComputerEvent_TerminalPrint terminal_print;
    } type;
} fdbg_ComputerEvent;

typedef PB_BYTES_ARRAY_T(8) fdbg_ComputerStatus_stack_t;
typedef struct _fdbg_ComputerStatus {
    uint64_t pc; /* program counter */
    pb_size_t registers_count;
    uint64_t registers[32];
    pb_size_t flags_count;
    bool flags[24];
    fdbg_ComputerStatus_stack_t stack;
    pb_size_t events_count;
    fdbg_ComputerEvent events[4];
} fdbg_ComputerStatus;

typedef struct _fdbg_RunStatus {
    bool running;
    uint64_t pc;
    pb_size_t events_count;
    fdbg_ComputerEvent events[36];
} fdbg_RunStatus;

typedef struct _fdbg_Debug {
    char text[255];
} fdbg_Debug;

typedef struct _fdbg_ToDebugger {
    fdbg_Status status;
    pb_size_t which_message;
    union {
        fdbg_AckResponse ack_response;
        fdbg_WriteMemoryResponse write_memory_response;
        fdbg_ReadMemoryResponse read_memory_response;
        fdbg_ComputerStatus computer_status;
        fdbg_BreakpointList breakpoint_list;
        fdbg_CycleResponse cycle_response;
        fdbg_RunStatus run_status;
        fdbg_Debug debug;
    } message;
} fdbg_ToDebugger;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _fdbg_Status_MIN fdbg_Status_OK
#define _fdbg_Status_MAX fdbg_Status_CPU_INVALID_INSTRUCTION
#define _fdbg_Status_ARRAYSIZE ((fdbg_Status)(fdbg_Status_CPU_INVALID_INSTRUCTION+1))












#define fdbg_ToDebugger_status_ENUMTYPE fdbg_Status


/* Initializer values for message structs */
#define fdbg_AckResponse_init_default            {0, 0, 0, 0}
#define fdbg_WriteMemoryResponse_init_default    {0}
#define fdbg_ReadMemoryResponse_init_default     {0, {0, {0}}}
#define fdbg_ComputerStatus_init_default         {0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, {0}}, 0, {fdbg_ComputerEvent_init_default, fdbg_ComputerEvent_init_default, fdbg_ComputerEvent_init_default, fdbg_ComputerEvent_init_default}}
#define fdbg_OptionalUint_init_default           {0, 0}
#define fdbg_CycleResponse_init_default          {0, 0, {fdbg_OptionalUint_init_default, fdbg_OptionalUint_init_default, fdbg_OptionalUint_init_default, fdbg_OptionalUint_init_default, fdbg_OptionalUint_init_default, fdbg_OptionalUint_init_default, fdbg_OptionalUint_init_default, fdbg_OptionalUint_init_default, fdbg_OptionalUint_init_default, fdbg_OptionalUint_init_default, fdbg_OptionalUint_init_default, fdbg_OptionalUint_init_default, fdbg_OptionalUint_init_default, fdbg_OptionalUint_init_default, fdbg_OptionalUint_init_default, fdbg_OptionalUint_init_default}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define fdbg_BreakpointList_init_default         {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define fdbg_ComputerEvent_init_default          {0, {fdbg_ComputerEvent_TerminalPrint_init_default}}
#define fdbg_ComputerEvent_TerminalPrint_init_default {""}
#define fdbg_RunStatus_init_default              {0, 0, 0, {fdbg_ComputerEvent_init_default, fdbg_ComputerEvent_init_default, fdbg_ComputerEvent_init_default, fdbg_ComputerEvent_init_default, fdbg_ComputerEvent_init_default, fdbg_ComputerEvent_init_default, fdbg_ComputerEvent_init_default, fdbg_ComputerEvent_init_default, fdbg_ComputerEvent_init_default, fdbg_ComputerEvent_init_default, fdbg_ComputerEvent_init_default, fdbg_ComputerEvent_init_default, fdbg_ComputerEvent_init_default, fdbg_ComputerEvent_init_default, fdbg_ComputerEvent_init_default, fdbg_ComputerEvent_init_default, fdbg_ComputerEvent_init_default, fdbg_ComputerEvent_init_default, fdbg_ComputerEvent_init_default, fdbg_ComputerEvent_init_default, fdbg_ComputerEvent_init_default, fdbg_ComputerEvent_init_default, fdbg_ComputerEvent_init_default, fdbg_ComputerEvent_init_default, fdbg_ComputerEvent_init_default, fdbg_ComputerEvent_init_default, fdbg_ComputerEvent_init_default, fdbg_ComputerEvent_init_default, fdbg_ComputerEvent_init_default, fdbg_ComputerEvent_init_default, fdbg_ComputerEvent_init_default, fdbg_ComputerEvent_init_default, fdbg_ComputerEvent_init_default, fdbg_ComputerEvent_init_default, fdbg_ComputerEvent_init_default, fdbg_ComputerEvent_init_default}}
#define fdbg_Debug_init_default                  {""}
#define fdbg_ToDebugger_init_default             {_fdbg_Status_MIN, 0, {fdbg_AckResponse_init_default}}
#define fdbg_AckResponse_init_zero               {0, 0, 0, 0}
#define fdbg_WriteMemoryResponse_init_zero       {0}
#define fdbg_ReadMemoryResponse_init_zero        {0, {0, {0}}}
#define fdbg_ComputerStatus_init_zero            {0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, {0}}, 0, {fdbg_ComputerEvent_init_zero, fdbg_ComputerEvent_init_zero, fdbg_ComputerEvent_init_zero, fdbg_ComputerEvent_init_zero}}
#define fdbg_OptionalUint_init_zero              {0, 0}
#define fdbg_CycleResponse_init_zero             {0, 0, {fdbg_OptionalUint_init_zero, fdbg_OptionalUint_init_zero, fdbg_OptionalUint_init_zero, fdbg_OptionalUint_init_zero, fdbg_OptionalUint_init_zero, fdbg_OptionalUint_init_zero, fdbg_OptionalUint_init_zero, fdbg_OptionalUint_init_zero, fdbg_OptionalUint_init_zero, fdbg_OptionalUint_init_zero, fdbg_OptionalUint_init_zero, fdbg_OptionalUint_init_zero, fdbg_OptionalUint_init_zero, fdbg_OptionalUint_init_zero, fdbg_OptionalUint_init_zero, fdbg_OptionalUint_init_zero}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define fdbg_BreakpointList_init_zero            {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define fdbg_ComputerEvent_init_zero             {0, {fdbg_ComputerEvent_TerminalPrint_init_zero}}
#define fdbg_ComputerEvent_TerminalPrint_init_zero {""}
#define fdbg_RunStatus_init_zero                 {0, 0, 0, {fdbg_ComputerEvent_init_zero, fdbg_ComputerEvent_init_zero, fdbg_ComputerEvent_init_zero, fdbg_ComputerEvent_init_zero, fdbg_ComputerEvent_init_zero, fdbg_ComputerEvent_init_zero, fdbg_ComputerEvent_init_zero, fdbg_ComputerEvent_init_zero, fdbg_ComputerEvent_init_zero, fdbg_ComputerEvent_init_zero, fdbg_ComputerEvent_init_zero, fdbg_ComputerEvent_init_zero, fdbg_ComputerEvent_init_zero, fdbg_ComputerEvent_init_zero, fdbg_ComputerEvent_init_zero, fdbg_ComputerEvent_init_zero, fdbg_ComputerEvent_init_zero, fdbg_ComputerEvent_init_zero, fdbg_ComputerEvent_init_zero, fdbg_ComputerEvent_init_zero, fdbg_ComputerEvent_init_zero, fdbg_ComputerEvent_init_zero, fdbg_ComputerEvent_init_zero, fdbg_ComputerEvent_init_zero, fdbg_ComputerEvent_init_zero, fdbg_ComputerEvent_init_zero, fdbg_ComputerEvent_init_zero, fdbg_ComputerEvent_init_zero, fdbg_ComputerEvent_init_zero, fdbg_ComputerEvent_init_zero, fdbg_ComputerEvent_init_zero, fdbg_ComputerEvent_init_zero, fdbg_ComputerEvent_init_zero, fdbg_ComputerEvent_init_zero, fdbg_ComputerEvent_init_zero, fdbg_ComputerEvent_init_zero}}
#define fdbg_Debug_init_zero                     {""}
#define fdbg_ToDebugger_init_zero                {_fdbg_Status_MIN, 0, {fdbg_AckResponse_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define fdbg_AckResponse_id_tag                  1
#define fdbg_AckResponse_server_sz_tag           2
#define fdbg_AckResponse_to_computer_sz_tag      3
#define fdbg_AckResponse_to_debugger_sz_tag      4
#define fdbg_WriteMemoryResponse_first_failed_pos_tag 1
#define fdbg_ReadMemoryResponse_initial_pos_tag  1
#define fdbg_ReadMemoryResponse_bytes_tag        2
#define fdbg_OptionalUint_has_tag                1
#define fdbg_OptionalUint_value_tag              2
#define fdbg_CycleResponse_pc_tag                1
#define fdbg_CycleResponse_bytes_tag             2
#define fdbg_CycleResponse_bits_tag              3
#define fdbg_BreakpointList_addr_tag             1
#define fdbg_ComputerEvent_TerminalPrint_text_tag 1
#define fdbg_ComputerEvent_terminal_print_tag    1
#define fdbg_ComputerStatus_pc_tag               1
#define fdbg_ComputerStatus_registers_tag        2
#define fdbg_ComputerStatus_flags_tag            3
#define fdbg_ComputerStatus_stack_tag            4
#define fdbg_ComputerStatus_events_tag           5
#define fdbg_RunStatus_running_tag               1
#define fdbg_RunStatus_pc_tag                    2
#define fdbg_RunStatus_events_tag                3
#define fdbg_Debug_text_tag                      1
#define fdbg_ToDebugger_status_tag               1
#define fdbg_ToDebugger_ack_response_tag         2
#define fdbg_ToDebugger_write_memory_response_tag 3
#define fdbg_ToDebugger_read_memory_response_tag 4
#define fdbg_ToDebugger_computer_status_tag      5
#define fdbg_ToDebugger_breakpoint_list_tag      6
#define fdbg_ToDebugger_cycle_response_tag       7
#define fdbg_ToDebugger_run_status_tag           8
#define fdbg_ToDebugger_debug_tag                9

/* Struct field encoding specification for nanopb */
#define fdbg_AckResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1) \
X(a, STATIC,   SINGULAR, UINT32,   server_sz,         2) \
X(a, STATIC,   SINGULAR, UINT32,   to_computer_sz,    3) \
X(a, STATIC,   SINGULAR, UINT32,   to_debugger_sz,    4)
#define fdbg_AckResponse_CALLBACK NULL
#define fdbg_AckResponse_DEFAULT NULL

#define fdbg_WriteMemoryResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   first_failed_pos,   1)
#define fdbg_WriteMemoryResponse_CALLBACK NULL
#define fdbg_WriteMemoryResponse_DEFAULT NULL

#define fdbg_ReadMemoryResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   initial_pos,       1) \
X(a, STATIC,   SINGULAR, BYTES,    bytes,             2)
#define fdbg_ReadMemoryResponse_CALLBACK NULL
#define fdbg_ReadMemoryResponse_DEFAULT NULL

#define fdbg_ComputerStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   pc,                1) \
X(a, STATIC,   REPEATED, UINT64,   registers,         2) \
X(a, STATIC,   REPEATED, BOOL,     flags,             3) \
X(a, STATIC,   SINGULAR, BYTES,    stack,             4) \
X(a, STATIC,   REPEATED, MESSAGE,  events,            5)
#define fdbg_ComputerStatus_CALLBACK NULL
#define fdbg_ComputerStatus_DEFAULT NULL
#define fdbg_ComputerStatus_events_MSGTYPE fdbg_ComputerEvent

#define fdbg_OptionalUint_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     has,               1) \
X(a, STATIC,   SINGULAR, UINT64,   value,             2)
#define fdbg_OptionalUint_CALLBACK NULL
#define fdbg_OptionalUint_DEFAULT NULL

#define fdbg_CycleResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   pc,                1) \
X(a, STATIC,   REPEATED, MESSAGE,  bytes,             2) \
X(a, STATIC,   REPEATED, BOOL,     bits,              3)
#define fdbg_CycleResponse_CALLBACK NULL
#define fdbg_CycleResponse_DEFAULT NULL
#define fdbg_CycleResponse_bytes_MSGTYPE fdbg_OptionalUint

#define fdbg_BreakpointList_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, UINT64,   addr,              1)
#define fdbg_BreakpointList_CALLBACK NULL
#define fdbg_BreakpointList_DEFAULT NULL

#define fdbg_ComputerEvent_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,terminal_print,type.terminal_print),   1)
#define fdbg_ComputerEvent_CALLBACK NULL
#define fdbg_ComputerEvent_DEFAULT NULL
#define fdbg_ComputerEvent_type_terminal_print_MSGTYPE fdbg_ComputerEvent_TerminalPrint

#define fdbg_ComputerEvent_TerminalPrint_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   text,              1)
#define fdbg_ComputerEvent_TerminalPrint_CALLBACK NULL
#define fdbg_ComputerEvent_TerminalPrint_DEFAULT NULL

#define fdbg_RunStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     running,           1) \
X(a, STATIC,   SINGULAR, UINT64,   pc,                2) \
X(a, STATIC,   REPEATED, MESSAGE,  events,            3)
#define fdbg_RunStatus_CALLBACK NULL
#define fdbg_RunStatus_DEFAULT NULL
#define fdbg_RunStatus_events_MSGTYPE fdbg_ComputerEvent

#define fdbg_Debug_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   text,              1)
#define fdbg_Debug_CALLBACK NULL
#define fdbg_Debug_DEFAULT NULL

#define fdbg_ToDebugger_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    status,            1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,ack_response,message.ack_response),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,write_memory_response,message.write_memory_response),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,read_memory_response,message.read_memory_response),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,computer_status,message.computer_status),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,breakpoint_list,message.breakpoint_list),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,cycle_response,message.cycle_response),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,run_status,message.run_status),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,debug,message.debug),   9)
#define fdbg_ToDebugger_CALLBACK NULL
#define fdbg_ToDebugger_DEFAULT NULL
#define fdbg_ToDebugger_message_ack_response_MSGTYPE fdbg_AckResponse
#define fdbg_ToDebugger_message_write_memory_response_MSGTYPE fdbg_WriteMemoryResponse
#define fdbg_ToDebugger_message_read_memory_response_MSGTYPE fdbg_ReadMemoryResponse
#define fdbg_ToDebugger_message_computer_status_MSGTYPE fdbg_ComputerStatus
#define fdbg_ToDebugger_message_breakpoint_list_MSGTYPE fdbg_BreakpointList
#define fdbg_ToDebugger_message_cycle_response_MSGTYPE fdbg_CycleResponse
#define fdbg_ToDebugger_message_run_status_MSGTYPE fdbg_RunStatus
#define fdbg_ToDebugger_message_debug_MSGTYPE fdbg_Debug

extern const pb_msgdesc_t fdbg_AckResponse_msg;
extern const pb_msgdesc_t fdbg_WriteMemoryResponse_msg;
extern const pb_msgdesc_t fdbg_ReadMemoryResponse_msg;
extern const pb_msgdesc_t fdbg_ComputerStatus_msg;
extern const pb_msgdesc_t fdbg_OptionalUint_msg;
extern const pb_msgdesc_t fdbg_CycleResponse_msg;
extern const pb_msgdesc_t fdbg_BreakpointList_msg;
extern const pb_msgdesc_t fdbg_ComputerEvent_msg;
extern const pb_msgdesc_t fdbg_ComputerEvent_TerminalPrint_msg;
extern const pb_msgdesc_t fdbg_RunStatus_msg;
extern const pb_msgdesc_t fdbg_Debug_msg;
extern const pb_msgdesc_t fdbg_ToDebugger_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define fdbg_AckResponse_fields &fdbg_AckResponse_msg
#define fdbg_WriteMemoryResponse_fields &fdbg_WriteMemoryResponse_msg
#define fdbg_ReadMemoryResponse_fields &fdbg_ReadMemoryResponse_msg
#define fdbg_ComputerStatus_fields &fdbg_ComputerStatus_msg
#define fdbg_OptionalUint_fields &fdbg_OptionalUint_msg
#define fdbg_CycleResponse_fields &fdbg_CycleResponse_msg
#define fdbg_BreakpointList_fields &fdbg_BreakpointList_msg
#define fdbg_ComputerEvent_fields &fdbg_ComputerEvent_msg
#define fdbg_ComputerEvent_TerminalPrint_fields &fdbg_ComputerEvent_TerminalPrint_msg
#define fdbg_RunStatus_fields &fdbg_RunStatus_msg
#define fdbg_Debug_fields &fdbg_Debug_msg
#define fdbg_ToDebugger_fields &fdbg_ToDebugger_msg

/* Maximum encoded size of messages (where known) */
#define FDBG_PROTOBUF_TO_DEBUGGER_NANOPB_H_MAX_SIZE fdbg_ToDebugger_size
#define fdbg_AckResponse_size                    24
#define fdbg_BreakpointList_size                 176
#define fdbg_ComputerEvent_TerminalPrint_size    9
#define fdbg_ComputerEvent_size                  11
#define fdbg_ComputerStatus_size                 473
#define fdbg_CycleResponse_size                  299
#define fdbg_Debug_size                          257
#define fdbg_OptionalUint_size                   13
#define fdbg_ReadMemoryResponse_size             77
#define fdbg_RunStatus_size                      481
#define fdbg_ToDebugger_size                     486
#define fdbg_WriteMemoryResponse_size            11

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
